stages: 
  load_data:
    cmd: python3 src/prepare_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/prepare_data.py
    - data_given/online_shoppers_intention.csv
    outs:
    - data/raw/raw_data.csv

  split_data:
    cmd: python3 src/split_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/split_data.py
    - data/raw/raw_data.csv
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv

  train_and_evaluate:
    cmd: python3 src/split_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/train_and_evaluate.py
    metrics:
    - report/scores.json:
        cache: false
    outs:
    - saved_models/best_model.joblib