base:
  random_state: 45

datasource:
  given: data_given/online_shoppers_intention.csv

data:
  raw_data: data/raw/raw_data.csv

split_data:
  train_path: data/processed/train_data.csv
  test_path: data/processed/test_data.csv
  test_size: 0.2

reports:
  scores: report/scores.json

estimators:
  n_estimators: 100

app model dir: prediction_service/model/best_model.joblib